---
title: "Copula"
author: "Aleksandra Muciek"
date: "2023-06-20"
categories: [Math, theory]
toc: true
format: 
    html: 
        code-fold: true
---

What are copulas? Why do we need them? How do we use them?

## Copulae - what are they?

Copulae came from the need of modeling relations between random variables. 

Assume we have random variables $X$ and $Y$ with distributions $F_X$ and $F_Y$. If they are independent, their joint distribution is given as $F_{X,Y}(x, y) = F_X(x)F_Y(y)$. But what if they are not independent? There are numerous ways the variables could influence each other.

Here comes Copula.

Every cumulative distribution function with uniform marginals on $U[0,1]$ is called copula. Why is this is useful? Because we know that $F_X(X)$ is uniformly distributed on $[0,1]$. With random variables $X$, $Y$ we can go to uniform random variables by $F_X(X)$, $F_Y(Y)$ and explore their dependance there, on $[0, 1] \times [0,1]$.

## Existence

Can we do that trick for any pair of $X$ and $Y$? It turns out that yes. 

Sklar theorem

::: {#thm-line}

## Sklar

If $F_{(X,Y)}$ is a cdf function of random variables $(X, Y)$ with continuous marginal cdfs $F_X$ and $F_Y$, there exists unique Copula such that

$$
F_{(X, Y)}(x, y) = C_{(X,Y)}(F_X(x), F_Y(y))
$$
:::

:::{.proof}
Take
$$
C_(X, Y)(x, y) := P[F_X(X) \leq x, F_Y(Y) \leq y],
$$
then
$$
C_(X, Y)(x, y) = F_{(X,Y)} (F^{-1}_X(x), F^{-1}_Y(y)).
$$
:::

## Examples

Important examples:


1. Independent $X$ and $Y$
    $$
    C^{*} (x, y) = \min (1, x) \min (1, y) I_{(0, \infty) \times (0, \infty)} (x, y)
    $$


```{python}

import numpy as np
import matplotlib.pyplot as plt

def plot_copula(copula_function, copula_name):
    x = np.linspace(0, 1, 30)
    y = np.linspace(0, 1, 30)
    X, Y = np.meshgrid(x, y)
    Z = copula_function(X, Y)


    fig = plt.figure()
    ax = plt.axes(projection='3d')
    ax.contour3D(X, Y, Z, 50) #, cmap='binary')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title(copula_name)
    #ax.set_zlabel('Copula')

def c_star(x, y):
    return np.minimum([1], x) * np.minimum([1],y)


plot_copula(c_star, "C*")

```

2. Copula plus $C^{+}$
    This corresponds to maximal dependence between two variables.
    $$
    C^{+} = \min( \min(1, x), \min(1, y)) I_{(0, \infty) \times (0, \infty)} (x, y)
    $$

```{python}
def c_plus(x, y):
    return np.minimum(np.minimum([1], x), np.minimum([1],y))


plot_copula(c_plus, "C+")
```

3. Copula minus $C^{-}$. This corresponds to maximal negative dependence between two variables.
    $$
    C^{-} = max(0, min(1, x) + min (1, y) - 1) I_{(0, \infty) \times (0, \infty)} (x, y)
    $$
```{python}
def c_minus(x, y):
    return np.maximum(0, np.minimum([1], x) + np.minimum([1],y) - 1)


plot_copula(c_minus, "C-")
```



## Properties

The copulae plus and minus bound every other copula:

::: {#thm-bound}

## Frechet

For any copula

$$
C^{-} (x, y) \leq C(x, y) \leq C^{-} (x, y), \forall x, y \in \mathbb{R}
$$
:::

As every density, copulae have properties:

* $C: \mathbb{R}^2 \to [0,1]$ is nondecreasing on every dimension
* $C(-\infty, -\infty) = 0$ and $C(\infty, \infty) = 1$, while iterating the limits in any order.
* $C$ satisfies

$$
C(\min(\mathbf{x},\mathbf{y})) + C(\max(\mathbf{x},\mathbf{y})) \geq C(\mathbf{x}) + C(\mathbf{y}).
$$





<!-- ## What is a copula?

They are objects that describe dependance between random variables. 

A copula is a multivariate distribution function for which the marginal probability distribution of each variable is uniform on the interval $[0,1]$. Copula describes relations between the variables - there is a theorem that states: *any multivariate joint distribution can be written in terms of univariate marginal distribution functions and a copula.*


 -->

## Sources:

* https://en.wikipedia.org/wiki/Copula_(probability_theory)#Sklar's_theorem
* http://www.math.uni.wroc.pl/~szekli/documents/mumio/mumio-16-trans/skrypt-16.pdf
* https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html
